#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

NESTO_ENV_FILE="${SCRIPT_DIR}/../.env"
if [ -f "${NESTO_ENV_FILE}" ]; then
    . "${NESTO_ENV_FILE}"
fi

(cd "${SCRIPT_DIR}/../src" && web-ext run --bc -u "${NESTO_DASHBOARD_URL}")